# Generated by Django 3.1.4 on 2020-12-13 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='о себе')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский'), ('O', 'Другой'), ('NS', 'Не выбран')], default='NS', max_length=2, verbose_name='дата')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='дата рождения')),
                ('native_city', models.CharField(blank=True, max_length=100, verbose_name='родной город')),
                ('languages', models.CharField(blank=True, max_length=100, verbose_name='языки')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, verbose_name='мобильный телефон')),
                ('add_phone', models.CharField(blank=True, max_length=50, verbose_name='доп. телефон')),
                ('skype', models.CharField(blank=True, max_length=100, verbose_name='skype')),
                ('personal_site', models.URLField(blank=True, verbose_name='личный сайт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
