# Generated by Django 3.1.4 on 2020-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.svg', upload_to='avatar/%Y/%m/%d/', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский'), ('O', 'Другой'), ('NS', 'Не выбран')], default='NS', max_length=2, verbose_name='пол'),
        ),
    ]
