# Generated by Django 3.1.4 on 2020-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_auto_20201213_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=100, verbose_name='профессия'),
        ),
    ]
