# Generated by Django 3.1.4 on 2020-12-19 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_auto_20201213_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user', 'job'], 'verbose_name': 'профиль', 'verbose_name_plural': 'профиля'},
        ),
    ]
